travis:
  secure:
    BINSTAR_TOKEN: ioapJTm0siKfQmjhjNeLnJ7HLCfBTGPiP5i8FAmO0/44C0ZUDhF/28rzkp4Sd0Mzomy3jG9IxCtNJHfrFiDCamZDWkz+jiMw5GNUQb3VZDn5Ntp1dcTKWNmDaGNMmWDInFbr72aRAHzIJwefEBJD4MiMiNzb2UHrfeJAA5wuitGJTzyp0ECIsXLXBWZHkjqlWvvn5FK7QssCiUjjkCVnbDFNN26t4mDfP9lmdm/TQ3+4jUnE0rrmWwxXOgZJpCd02MINOeQsXGkyQMvfxXcxwkSOT855hXwUmaFh3I9cW+Y2DN1dg1SSBXxyTbzwLrgZgJRlUQ4oR/zL+t0sVzh3h4jiVVOnyj66bgnwp+AMvGis7CDhx8merqO+8i+Wsqsjd+BPPiEdpCylUasBUZEe1t16/iy2Hqluae7N3S253wFa9CjpyqaEyH3tlJN8EXbKII60aYsw7Ne+PnZDeAIWEuqo/0aRUu7HIkagriVJwKii2bfilfIpmrRVb5yothqborOzICyQ5yi383hZ2FVCcHLCmgrneSBZn8Ire35GMz1fHKqcvt/zkP+s4jK44Oy22sY81+pfU4eUtT11qfhSuMtD+cdNOCstv2MVBvsZNZNe5LhGM4VPmQPUs8kxacfkF5JZeyo3iUuqm5xVV629QszJmiaVci745y1/JDVUW1o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
